#!/usr/bin/python3
# SPDX-FileCopyrightText: 2022 Ryoma Minami　　　　　
# SPDX-License-Identifier: BSD-3-Clause

import sys

ans =0.0

for line in sys.stdin:
    if line != 0:
            ans += float(line)

print(ans)
